// Generated by tools/generate.py from GLFW 3.5.1. Do not edit.
// Core constants, types, callbacks, and wrappers not supplied by glfw.v.
// Regenerate with python3 tools/generate.py; raw results follow upstream ownership rules.
module glfw

import antono2.vulkan as vk

// GLFW constants. Values come from the pinned upstream header.
pub const version_major = 3
pub const version_minor = 5
pub const version_revision = 1
pub const hat_centered = 0
pub const hat_up = 1
pub const hat_right = 2
pub const hat_down = 4
pub const hat_left = 8
pub const hat_right_up = 3
pub const hat_right_down = 6
pub const hat_left_up = 9
pub const hat_left_down = 12
pub const key_unknown = -1
pub const key_apostrophe = 39
pub const key_comma = 44
pub const key_minus = 45
pub const key_period = 46
pub const key_slash = 47
pub const key_0 = 48
pub const key_1 = 49
pub const key_2 = 50
pub const key_3 = 51
pub const key_4 = 52
pub const key_5 = 53
pub const key_6 = 54
pub const key_7 = 55
pub const key_8 = 56
pub const key_9 = 57
pub const key_semicolon = 59
pub const key_equal = 61
pub const key_a = 65
pub const key_b = 66
pub const key_c = 67
pub const key_d = 68
pub const key_e = 69
pub const key_f = 70
pub const key_g = 71
pub const key_h = 72
pub const key_i = 73
pub const key_j = 74
pub const key_k = 75
pub const key_l = 76
pub const key_m = 77
pub const key_n = 78
pub const key_o = 79
pub const key_p = 80
pub const key_q = 81
pub const key_r = 82
pub const key_s = 83
pub const key_t = 84
pub const key_u = 85
pub const key_v = 86
pub const key_w = 87
pub const key_x = 88
pub const key_y = 89
pub const key_z = 90
pub const key_left_bracket = 91
pub const key_backslash = 92
pub const key_right_bracket = 93
pub const key_grave_accent = 96
pub const key_world_1 = 161
pub const key_world_2 = 162
pub const key_tab = 258
pub const key_backspace = 259
pub const key_insert = 260
pub const key_delete = 261
pub const key_right = 262
pub const key_left = 263
pub const key_down = 264
pub const key_up = 265
pub const key_page_up = 266
pub const key_page_down = 267
pub const key_home = 268
pub const key_end = 269
pub const key_caps_lock = 280
pub const key_scroll_lock = 281
pub const key_num_lock = 282
pub const key_print_screen = 283
pub const key_pause = 284
pub const key_f1 = 290
pub const key_f2 = 291
pub const key_f3 = 292
pub const key_f4 = 293
pub const key_f5 = 294
pub const key_f6 = 295
pub const key_f7 = 296
pub const key_f8 = 297
pub const key_f9 = 298
pub const key_f10 = 299
pub const key_f11 = 300
pub const key_f12 = 301
pub const key_f13 = 302
pub const key_f14 = 303
pub const key_f15 = 304
pub const key_f16 = 305
pub const key_f17 = 306
pub const key_f18 = 307
pub const key_f19 = 308
pub const key_f20 = 309
pub const key_f21 = 310
pub const key_f22 = 311
pub const key_f23 = 312
pub const key_f24 = 313
pub const key_f25 = 314
pub const key_kp_0 = 320
pub const key_kp_1 = 321
pub const key_kp_2 = 322
pub const key_kp_3 = 323
pub const key_kp_4 = 324
pub const key_kp_5 = 325
pub const key_kp_6 = 326
pub const key_kp_7 = 327
pub const key_kp_8 = 328
pub const key_kp_9 = 329
pub const key_kp_decimal = 330
pub const key_kp_divide = 331
pub const key_kp_multiply = 332
pub const key_kp_subtract = 333
pub const key_kp_add = 334
pub const key_kp_enter = 335
pub const key_kp_equal = 336
pub const key_left_shift = 340
pub const key_left_control = 341
pub const key_left_alt = 342
pub const key_left_super = 343
pub const key_right_shift = 344
pub const key_right_control = 345
pub const key_right_alt = 346
pub const key_right_super = 347
pub const key_menu = 348
pub const key_last = 348
pub const mod_shift = 1
pub const mod_control = 2
pub const mod_alt = 4
pub const mod_super = 8
pub const mod_caps_lock = 16
pub const mod_num_lock = 32
pub const mouse_button_1 = 0
pub const mouse_button_2 = 1
pub const mouse_button_3 = 2
pub const mouse_button_4 = 3
pub const mouse_button_5 = 4
pub const mouse_button_6 = 5
pub const mouse_button_7 = 6
pub const mouse_button_8 = 7
pub const mouse_button_last = 7
pub const mouse_button_left = 0
pub const mouse_button_right = 1
pub const mouse_button_middle = 2
pub const joystick_1 = 0
pub const joystick_2 = 1
pub const joystick_3 = 2
pub const joystick_4 = 3
pub const joystick_5 = 4
pub const joystick_6 = 5
pub const joystick_7 = 6
pub const joystick_8 = 7
pub const joystick_9 = 8
pub const joystick_10 = 9
pub const joystick_11 = 10
pub const joystick_12 = 11
pub const joystick_13 = 12
pub const joystick_14 = 13
pub const joystick_15 = 14
pub const joystick_16 = 15
pub const joystick_last = 15
pub const gamepad_button_a = 0
pub const gamepad_button_b = 1
pub const gamepad_button_x = 2
pub const gamepad_button_y = 3
pub const gamepad_button_left_bumper = 4
pub const gamepad_button_right_bumper = 5
pub const gamepad_button_back = 6
pub const gamepad_button_start = 7
pub const gamepad_button_guide = 8
pub const gamepad_button_left_thumb = 9
pub const gamepad_button_right_thumb = 10
pub const gamepad_button_dpad_up = 11
pub const gamepad_button_dpad_right = 12
pub const gamepad_button_dpad_down = 13
pub const gamepad_button_dpad_left = 14
pub const gamepad_button_last = 14
pub const gamepad_button_cross = 0
pub const gamepad_button_circle = 1
pub const gamepad_button_square = 2
pub const gamepad_button_triangle = 3
pub const gamepad_axis_left_x = 0
pub const gamepad_axis_left_y = 1
pub const gamepad_axis_right_x = 2
pub const gamepad_axis_right_y = 3
pub const gamepad_axis_left_trigger = 4
pub const gamepad_axis_right_trigger = 5
pub const gamepad_axis_last = 5
pub const no_error = 0
pub const not_initialized = 65537
pub const no_current_context = 65538
pub const invalid_enum = 65539
pub const invalid_value = 65540
pub const out_of_memory = 65541
pub const api_unavailable = 65542
pub const version_unavailable = 65543
pub const platform_error = 65544
pub const format_unavailable = 65545
pub const no_window_context = 65546
pub const cursor_unavailable = 65547
pub const feature_unavailable = 65548
pub const feature_unimplemented = 65549
pub const platform_unavailable = 65550
pub const focused = 131073
pub const visible = 131076
pub const decorated = 131077
pub const auto_iconify = 131078
pub const floating = 131079
pub const maximized = 131080
pub const center_cursor = 131081
pub const transparent_framebuffer = 131082
pub const hovered = 131083
pub const focus_on_show = 131084
pub const mouse_passthrough = 131085
pub const position_x = 131086
pub const position_y = 131087
pub const red_bits = 135169
pub const green_bits = 135170
pub const blue_bits = 135171
pub const alpha_bits = 135172
pub const depth_bits = 135173
pub const stencil_bits = 135174
pub const accum_red_bits = 135175
pub const accum_green_bits = 135176
pub const accum_blue_bits = 135177
pub const accum_alpha_bits = 135178
pub const aux_buffers = 135179
pub const stereo = 135180
pub const samples = 135181
pub const srgb_capable = 135182
pub const refresh_rate = 135183
pub const doublebuffer = 135184
pub const context_version_major = 139266
pub const context_version_minor = 139267
pub const context_revision = 139268
pub const context_robustness = 139269
pub const opengl_forward_compat = 139270
pub const context_debug = 139271
pub const opengl_debug_context = 139271
pub const opengl_profile = 139272
pub const context_release_behavior = 139273
pub const context_no_error = 139274
pub const context_creation_api = 139275
pub const scale_to_monitor = 139276
pub const scale_framebuffer = 139277
pub const cocoa_retina_framebuffer = 143361
pub const cocoa_frame_name = 143362
pub const cocoa_graphics_switching = 143363
pub const x11_class_name = 147457
pub const x11_instance_name = 147458
pub const win32_keyboard_menu = 151553
pub const win32_showdefault = 151554
pub const wayland_app_id = 155649
pub const opengl_api = 196609
pub const opengl_es_api = 196610
pub const no_robustness = 0
pub const no_reset_notification = 200705
pub const lose_context_on_reset = 200706
pub const opengl_any_profile = 0
pub const opengl_core_profile = 204801
pub const opengl_compat_profile = 204802
pub const cursor = 208897
pub const sticky_keys = 208898
pub const sticky_mouse_buttons = 208899
pub const lock_key_mods = 208900
pub const raw_mouse_motion = 208901
pub const unlimited_mouse_buttons = 208902
pub const cursor_normal = 212993
pub const cursor_hidden = 212994
pub const cursor_disabled = 212995
pub const cursor_captured = 212996
pub const any_release_behavior = 0
pub const release_behavior_flush = 217089
pub const release_behavior_none = 217090
pub const native_context_api = 221185
pub const egl_context_api = 221186
pub const osmesa_context_api = 221187
pub const angle_platform_type_none = 225281
pub const angle_platform_type_opengl = 225282
pub const angle_platform_type_opengles = 225283
pub const angle_platform_type_d3d9 = 225284
pub const angle_platform_type_d3d11 = 225285
pub const angle_platform_type_vulkan = 225287
pub const angle_platform_type_metal = 225288
pub const wayland_prefer_libdecor = 229377
pub const wayland_disable_libdecor = 229378
pub const any_position = u32(2147483648)
pub const arrow_cursor = 221185
pub const ibeam_cursor = 221186
pub const crosshair_cursor = 221187
pub const pointing_hand_cursor = 221188
pub const resize_ew_cursor = 221189
pub const resize_ns_cursor = 221190
pub const resize_nwse_cursor = 221191
pub const resize_nesw_cursor = 221192
pub const resize_all_cursor = 221193
pub const not_allowed_cursor = 221194
pub const hresize_cursor = 221189
pub const vresize_cursor = 221190
pub const hand_cursor = 221188
pub const connected = 262145
pub const disconnected = 262146
pub const joystick_hat_buttons = 327681
pub const angle_platform_type = 327682
pub const platform = 327683
pub const cocoa_chdir_resources = 331777
pub const cocoa_menubar = 331778
pub const x11_xcb_vulkan_surface = 335873
pub const wayland_libdecor = 339969
pub const any_platform = 393216
pub const platform_win32 = 393217
pub const platform_cocoa = 393218
pub const platform_wayland = 393219
pub const platform_x11 = 393220
pub const platform_null = 393221
pub const dont_care = -1

pub type Cursor = C.GLFWcursor

@[typedef]
pub struct C.GLFWcursor {}

pub type VideoMode = C.GLFWvidmode

@[typedef]
pub struct C.GLFWvidmode {
pub:
	width       i32
	height      i32
	redBits     i32
	greenBits   i32
	blueBits    i32
	refreshRate i32
}

pub type GammaRamp = C.GLFWgammaramp

@[typedef]
pub struct C.GLFWgammaramp {
pub:
	red   &u16
	green &u16
	blue  &u16
	size  u32
}

pub type Image = C.GLFWimage

@[typedef]
pub struct C.GLFWimage {
pub:
	width  i32
	height i32
	pixels &u8
}

pub type GamepadState = C.GLFWgamepadstate

@[typedef]
pub struct C.GLFWgamepadstate {
pub:
	buttons [15]u8
	axes    [6]f32
}

pub type Allocator = C.GLFWallocator

@[typedef]
pub struct C.GLFWallocator {
pub:
	allocate   GLFWallocatefun
	reallocate GLFWreallocatefun
	deallocate GLFWdeallocatefun
	user       voidptr
}

// Raw callback signatures. Register named functions with C-compatible lifetimes.
pub type GLFWglproc = fn ()

pub type GLFWvkproc = fn ()

pub type GLFWallocatefun = fn (arg0 usize, arg1 voidptr) voidptr

pub type GLFWreallocatefun = fn (arg0 voidptr, arg1 usize, arg2 voidptr) voidptr

pub type GLFWdeallocatefun = fn (arg0 voidptr, arg1 voidptr)

pub type GLFWwindowposfun = fn (arg0 &Window, arg1 i32, arg2 i32)

pub type GLFWwindowsizefun = fn (arg0 &Window, arg1 i32, arg2 i32)

pub type GLFWwindowclosefun = fn (arg0 &Window)

pub type GLFWwindowrefreshfun = fn (arg0 &Window)

pub type GLFWwindowfocusfun = fn (arg0 &Window, arg1 i32)

pub type GLFWwindowiconifyfun = fn (arg0 &Window, arg1 i32)

pub type GLFWwindowmaximizefun = fn (arg0 &Window, arg1 i32)

pub type GLFWframebuffersizefun = fn (arg0 &Window, arg1 i32, arg2 i32)

pub type GLFWwindowcontentscalefun = fn (arg0 &Window, arg1 f32, arg2 f32)

pub type GLFWmousebuttonfun = fn (arg0 &Window, arg1 i32, arg2 i32, arg3 i32)

pub type GLFWcursorposfun = fn (arg0 &Window, arg1 f64, arg2 f64)

pub type GLFWcursorenterfun = fn (arg0 &Window, arg1 i32)

pub type GLFWscrollfun = fn (arg0 &Window, arg1 f64, arg2 f64)

pub type GLFWkeyfun = fn (arg0 &Window, arg1 i32, arg2 i32, arg3 i32, arg4 i32)

pub type GLFWcharfun = fn (arg0 &Window, arg1 u32)

pub type GLFWcharmodsfun = fn (arg0 &Window, arg1 u32, arg2 i32)

pub type GLFWdropfun = fn (arg0 &Window, arg1 i32, arg2 &&char)

pub type GLFWmonitorfun = fn (arg0 &Monitor, arg1 i32)

pub type GLFWjoystickfun = fn (arg0 i32, arg1 i32)

// Core GLFW functions not already present in the handwritten compatibility API.

fn C.glfwInitHint(i32, i32)
pub fn init_hint(arg0 i32, arg1 i32) {
	C.glfwInitHint(arg0, arg1)
}

fn C.glfwInitAllocator(&Allocator)
pub fn init_allocator(arg0 &Allocator) {
	C.glfwInitAllocator(arg0)
}

fn C.glfwInitVulkanLoader(vk.PFN_vkGetInstanceProcAddr)
pub fn init_vulkan_loader(arg0 vk.PFN_vkGetInstanceProcAddr) {
	C.glfwInitVulkanLoader(arg0)
}

fn C.glfwGetVersion(&i32, &i32, &i32)
pub fn get_version(arg0 &i32, arg1 &i32, arg2 &i32) {
	C.glfwGetVersion(arg0, arg1, arg2)
}

fn C.glfwGetVersionString() &char
pub fn get_version_string() &char {
	return C.glfwGetVersionString()
}

fn C.glfwGetError(&&char) i32
pub fn get_error(arg0 &&char) i32 {
	return C.glfwGetError(arg0)
}

fn C.glfwGetPlatform() i32
pub fn get_platform() i32 {
	return C.glfwGetPlatform()
}

fn C.glfwPlatformSupported(i32) i32
pub fn platform_supported(arg0 i32) i32 {
	return C.glfwPlatformSupported(arg0)
}

fn C.glfwGetMonitors(&i32) &&Monitor
pub fn get_monitors(arg0 &i32) &&Monitor {
	return C.glfwGetMonitors(arg0)
}

fn C.glfwGetPrimaryMonitor() &Monitor
pub fn get_primary_monitor() &Monitor {
	return C.glfwGetPrimaryMonitor()
}

fn C.glfwGetMonitorPos(&Monitor, &i32, &i32)
pub fn get_monitor_pos(arg0 &Monitor, arg1 &i32, arg2 &i32) {
	C.glfwGetMonitorPos(arg0, arg1, arg2)
}

fn C.glfwGetMonitorWorkarea(&Monitor, &i32, &i32, &i32, &i32)
pub fn get_monitor_workarea(arg0 &Monitor, arg1 &i32, arg2 &i32, arg3 &i32, arg4 &i32) {
	C.glfwGetMonitorWorkarea(arg0, arg1, arg2, arg3, arg4)
}

fn C.glfwGetMonitorPhysicalSize(&Monitor, &i32, &i32)
pub fn get_monitor_physical_size(arg0 &Monitor, arg1 &i32, arg2 &i32) {
	C.glfwGetMonitorPhysicalSize(arg0, arg1, arg2)
}

fn C.glfwGetMonitorContentScale(&Monitor, &f32, &f32)
pub fn get_monitor_content_scale(arg0 &Monitor, arg1 &f32, arg2 &f32) {
	C.glfwGetMonitorContentScale(arg0, arg1, arg2)
}

fn C.glfwGetMonitorName(&Monitor) &char
pub fn get_monitor_name(arg0 &Monitor) &char {
	return C.glfwGetMonitorName(arg0)
}

fn C.glfwSetMonitorUserPointer(&Monitor, voidptr)
pub fn set_monitor_user_pointer(arg0 &Monitor, arg1 voidptr) {
	C.glfwSetMonitorUserPointer(arg0, arg1)
}

fn C.glfwGetMonitorUserPointer(&Monitor) voidptr
pub fn get_monitor_user_pointer(arg0 &Monitor) voidptr {
	return C.glfwGetMonitorUserPointer(arg0)
}

fn C.glfwSetMonitorCallback(GLFWmonitorfun) GLFWmonitorfun
pub fn set_monitor_callback(arg0 GLFWmonitorfun) GLFWmonitorfun {
	return C.glfwSetMonitorCallback(arg0)
}

fn C.glfwGetVideoModes(&Monitor, &i32) &VideoMode
pub fn get_video_modes(arg0 &Monitor, arg1 &i32) &VideoMode {
	return C.glfwGetVideoModes(arg0, arg1)
}

fn C.glfwGetVideoMode(&Monitor) &VideoMode
pub fn get_video_mode(arg0 &Monitor) &VideoMode {
	return C.glfwGetVideoMode(arg0)
}

fn C.glfwSetGamma(&Monitor, f32)
pub fn set_gamma(arg0 &Monitor, arg1 f32) {
	C.glfwSetGamma(arg0, arg1)
}

fn C.glfwGetGammaRamp(&Monitor) &GammaRamp
pub fn get_gamma_ramp(arg0 &Monitor) &GammaRamp {
	return C.glfwGetGammaRamp(arg0)
}

fn C.glfwSetGammaRamp(&Monitor, &GammaRamp)
pub fn set_gamma_ramp(arg0 &Monitor, arg1 &GammaRamp) {
	C.glfwSetGammaRamp(arg0, arg1)
}

fn C.glfwDefaultWindowHints()
pub fn default_window_hints() {
	C.glfwDefaultWindowHints()
}

fn C.glfwWindowHintString(i32, &char)
pub fn window_hint_string(arg0 i32, arg1 &char) {
	C.glfwWindowHintString(arg0, arg1)
}

fn C.glfwGetWindowTitle(&Window) &char
pub fn get_window_title(arg0 &Window) &char {
	return C.glfwGetWindowTitle(arg0)
}

fn C.glfwSetWindowTitle(&Window, &char)
pub fn set_window_title(arg0 &Window, arg1 &char) {
	C.glfwSetWindowTitle(arg0, arg1)
}

fn C.glfwSetWindowIcon(&Window, i32, &Image)
pub fn set_window_icon(arg0 &Window, arg1 i32, arg2 &Image) {
	C.glfwSetWindowIcon(arg0, arg1, arg2)
}

fn C.glfwGetWindowPos(&Window, &i32, &i32)
pub fn get_window_pos(arg0 &Window, arg1 &i32, arg2 &i32) {
	C.glfwGetWindowPos(arg0, arg1, arg2)
}

fn C.glfwSetWindowPos(&Window, i32, i32)
pub fn set_window_pos(arg0 &Window, arg1 i32, arg2 i32) {
	C.glfwSetWindowPos(arg0, arg1, arg2)
}

fn C.glfwGetWindowSize(&Window, &i32, &i32)
pub fn get_window_size(arg0 &Window, arg1 &i32, arg2 &i32) {
	C.glfwGetWindowSize(arg0, arg1, arg2)
}

fn C.glfwSetWindowSizeLimits(&Window, i32, i32, i32, i32)
pub fn set_window_size_limits(arg0 &Window, arg1 i32, arg2 i32, arg3 i32, arg4 i32) {
	C.glfwSetWindowSizeLimits(arg0, arg1, arg2, arg3, arg4)
}

fn C.glfwSetWindowAspectRatio(&Window, i32, i32)
pub fn set_window_aspect_ratio(arg0 &Window, arg1 i32, arg2 i32) {
	C.glfwSetWindowAspectRatio(arg0, arg1, arg2)
}

fn C.glfwSetWindowSize(&Window, i32, i32)
pub fn set_window_size(arg0 &Window, arg1 i32, arg2 i32) {
	C.glfwSetWindowSize(arg0, arg1, arg2)
}

fn C.glfwGetWindowFrameSize(&Window, &i32, &i32, &i32, &i32)
pub fn get_window_frame_size(arg0 &Window, arg1 &i32, arg2 &i32, arg3 &i32, arg4 &i32) {
	C.glfwGetWindowFrameSize(arg0, arg1, arg2, arg3, arg4)
}

fn C.glfwGetWindowContentScale(&Window, &f32, &f32)
pub fn get_window_content_scale(arg0 &Window, arg1 &f32, arg2 &f32) {
	C.glfwGetWindowContentScale(arg0, arg1, arg2)
}

fn C.glfwGetWindowOpacity(&Window) f32
pub fn get_window_opacity(arg0 &Window) f32 {
	return C.glfwGetWindowOpacity(arg0)
}

fn C.glfwSetWindowOpacity(&Window, f32)
pub fn set_window_opacity(arg0 &Window, arg1 f32) {
	C.glfwSetWindowOpacity(arg0, arg1)
}

fn C.glfwIconifyWindow(&Window)
pub fn iconify_window(arg0 &Window) {
	C.glfwIconifyWindow(arg0)
}

fn C.glfwRestoreWindow(&Window)
pub fn restore_window(arg0 &Window) {
	C.glfwRestoreWindow(arg0)
}

fn C.glfwMaximizeWindow(&Window)
pub fn maximize_window(arg0 &Window) {
	C.glfwMaximizeWindow(arg0)
}

fn C.glfwShowWindow(&Window)
pub fn show_window(arg0 &Window) {
	C.glfwShowWindow(arg0)
}

fn C.glfwHideWindow(&Window)
pub fn hide_window(arg0 &Window) {
	C.glfwHideWindow(arg0)
}

fn C.glfwFocusWindow(&Window)
pub fn focus_window(arg0 &Window) {
	C.glfwFocusWindow(arg0)
}

fn C.glfwRequestWindowAttention(&Window)
pub fn request_window_attention(arg0 &Window) {
	C.glfwRequestWindowAttention(arg0)
}

fn C.glfwGetWindowMonitor(&Window) &Monitor
pub fn get_window_monitor(arg0 &Window) &Monitor {
	return C.glfwGetWindowMonitor(arg0)
}

fn C.glfwSetWindowMonitor(&Window, &Monitor, i32, i32, i32, i32, i32)
pub fn set_window_monitor(arg0 &Window, arg1 &Monitor, arg2 i32, arg3 i32, arg4 i32, arg5 i32, arg6 i32) {
	C.glfwSetWindowMonitor(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

fn C.glfwSetWindowAttrib(&Window, i32, i32)
pub fn set_window_attrib(arg0 &Window, arg1 i32, arg2 i32) {
	C.glfwSetWindowAttrib(arg0, arg1, arg2)
}

fn C.glfwSetWindowPosCallback(&Window, GLFWwindowposfun) GLFWwindowposfun
pub fn set_window_pos_callback(arg0 &Window, arg1 GLFWwindowposfun) GLFWwindowposfun {
	return C.glfwSetWindowPosCallback(arg0, arg1)
}

fn C.glfwSetWindowSizeCallback(&Window, GLFWwindowsizefun) GLFWwindowsizefun
pub fn set_window_size_callback(arg0 &Window, arg1 GLFWwindowsizefun) GLFWwindowsizefun {
	return C.glfwSetWindowSizeCallback(arg0, arg1)
}

fn C.glfwSetWindowCloseCallback(&Window, GLFWwindowclosefun) GLFWwindowclosefun
pub fn set_window_close_callback(arg0 &Window, arg1 GLFWwindowclosefun) GLFWwindowclosefun {
	return C.glfwSetWindowCloseCallback(arg0, arg1)
}

fn C.glfwSetWindowRefreshCallback(&Window, GLFWwindowrefreshfun) GLFWwindowrefreshfun
pub fn set_window_refresh_callback(arg0 &Window, arg1 GLFWwindowrefreshfun) GLFWwindowrefreshfun {
	return C.glfwSetWindowRefreshCallback(arg0, arg1)
}

fn C.glfwSetWindowFocusCallback(&Window, GLFWwindowfocusfun) GLFWwindowfocusfun
pub fn set_window_focus_callback(arg0 &Window, arg1 GLFWwindowfocusfun) GLFWwindowfocusfun {
	return C.glfwSetWindowFocusCallback(arg0, arg1)
}

fn C.glfwSetWindowIconifyCallback(&Window, GLFWwindowiconifyfun) GLFWwindowiconifyfun
pub fn set_window_iconify_callback(arg0 &Window, arg1 GLFWwindowiconifyfun) GLFWwindowiconifyfun {
	return C.glfwSetWindowIconifyCallback(arg0, arg1)
}

fn C.glfwSetWindowMaximizeCallback(&Window, GLFWwindowmaximizefun) GLFWwindowmaximizefun
pub fn set_window_maximize_callback(arg0 &Window, arg1 GLFWwindowmaximizefun) GLFWwindowmaximizefun {
	return C.glfwSetWindowMaximizeCallback(arg0, arg1)
}

fn C.glfwSetFramebufferSizeCallback(&Window, GLFWframebuffersizefun) GLFWframebuffersizefun
pub fn set_framebuffer_size_callback(arg0 &Window, arg1 GLFWframebuffersizefun) GLFWframebuffersizefun {
	return C.glfwSetFramebufferSizeCallback(arg0, arg1)
}

fn C.glfwSetWindowContentScaleCallback(&Window, GLFWwindowcontentscalefun) GLFWwindowcontentscalefun
pub fn set_window_content_scale_callback(arg0 &Window, arg1 GLFWwindowcontentscalefun) GLFWwindowcontentscalefun {
	return C.glfwSetWindowContentScaleCallback(arg0, arg1)
}

fn C.glfwWaitEvents()
pub fn wait_events() {
	C.glfwWaitEvents()
}

fn C.glfwWaitEventsTimeout(f64)
pub fn wait_events_timeout(arg0 f64) {
	C.glfwWaitEventsTimeout(arg0)
}

fn C.glfwPostEmptyEvent()
pub fn post_empty_event() {
	C.glfwPostEmptyEvent()
}

fn C.glfwGetInputMode(&Window, i32) i32
pub fn get_input_mode(arg0 &Window, arg1 i32) i32 {
	return C.glfwGetInputMode(arg0, arg1)
}

fn C.glfwSetInputMode(&Window, i32, i32)
pub fn set_input_mode(arg0 &Window, arg1 i32, arg2 i32) {
	C.glfwSetInputMode(arg0, arg1, arg2)
}

fn C.glfwRawMouseMotionSupported() i32
pub fn raw_mouse_motion_supported() i32 {
	return C.glfwRawMouseMotionSupported()
}

fn C.glfwGetKeyName(i32, i32) &char
pub fn get_key_name(arg0 i32, arg1 i32) &char {
	return C.glfwGetKeyName(arg0, arg1)
}

fn C.glfwGetKeyScancode(i32) i32
pub fn get_key_scancode(arg0 i32) i32 {
	return C.glfwGetKeyScancode(arg0)
}

fn C.glfwGetMouseButton(&Window, i32) i32
pub fn get_mouse_button(arg0 &Window, arg1 i32) i32 {
	return C.glfwGetMouseButton(arg0, arg1)
}

fn C.glfwGetCursorPos(&Window, &f64, &f64)
pub fn get_cursor_pos(arg0 &Window, arg1 &f64, arg2 &f64) {
	C.glfwGetCursorPos(arg0, arg1, arg2)
}

fn C.glfwSetCursorPos(&Window, f64, f64)
pub fn set_cursor_pos(arg0 &Window, arg1 f64, arg2 f64) {
	C.glfwSetCursorPos(arg0, arg1, arg2)
}

fn C.glfwCreateCursor(&Image, i32, i32) &Cursor
pub fn create_cursor(arg0 &Image, arg1 i32, arg2 i32) &Cursor {
	return C.glfwCreateCursor(arg0, arg1, arg2)
}

fn C.glfwCreateStandardCursor(i32) &Cursor
pub fn create_standard_cursor(arg0 i32) &Cursor {
	return C.glfwCreateStandardCursor(arg0)
}

fn C.glfwDestroyCursor(&Cursor)
pub fn destroy_cursor(arg0 &Cursor) {
	C.glfwDestroyCursor(arg0)
}

fn C.glfwSetCursor(&Window, &Cursor)
pub fn set_cursor(arg0 &Window, arg1 &Cursor) {
	C.glfwSetCursor(arg0, arg1)
}

fn C.glfwSetCharCallback(&Window, GLFWcharfun) GLFWcharfun
pub fn set_char_callback(arg0 &Window, arg1 GLFWcharfun) GLFWcharfun {
	return C.glfwSetCharCallback(arg0, arg1)
}

fn C.glfwSetCharModsCallback(&Window, GLFWcharmodsfun) GLFWcharmodsfun
pub fn set_char_mods_callback(arg0 &Window, arg1 GLFWcharmodsfun) GLFWcharmodsfun {
	return C.glfwSetCharModsCallback(arg0, arg1)
}

fn C.glfwSetMouseButtonCallback(&Window, GLFWmousebuttonfun) GLFWmousebuttonfun
pub fn set_mouse_button_callback(arg0 &Window, arg1 GLFWmousebuttonfun) GLFWmousebuttonfun {
	return C.glfwSetMouseButtonCallback(arg0, arg1)
}

fn C.glfwSetCursorPosCallback(&Window, GLFWcursorposfun) GLFWcursorposfun
pub fn set_cursor_pos_callback(arg0 &Window, arg1 GLFWcursorposfun) GLFWcursorposfun {
	return C.glfwSetCursorPosCallback(arg0, arg1)
}

fn C.glfwSetCursorEnterCallback(&Window, GLFWcursorenterfun) GLFWcursorenterfun
pub fn set_cursor_enter_callback(arg0 &Window, arg1 GLFWcursorenterfun) GLFWcursorenterfun {
	return C.glfwSetCursorEnterCallback(arg0, arg1)
}

fn C.glfwSetScrollCallback(&Window, GLFWscrollfun) GLFWscrollfun
pub fn set_scroll_callback(arg0 &Window, arg1 GLFWscrollfun) GLFWscrollfun {
	return C.glfwSetScrollCallback(arg0, arg1)
}

fn C.glfwSetDropCallback(&Window, GLFWdropfun) GLFWdropfun
pub fn set_drop_callback(arg0 &Window, arg1 GLFWdropfun) GLFWdropfun {
	return C.glfwSetDropCallback(arg0, arg1)
}

fn C.glfwJoystickPresent(i32) i32
pub fn joystick_present(arg0 i32) i32 {
	return C.glfwJoystickPresent(arg0)
}

fn C.glfwGetJoystickAxes(i32, &i32) &f32
pub fn get_joystick_axes(arg0 i32, arg1 &i32) &f32 {
	return C.glfwGetJoystickAxes(arg0, arg1)
}

fn C.glfwGetJoystickButtons(i32, &i32) &u8
pub fn get_joystick_buttons(arg0 i32, arg1 &i32) &u8 {
	return C.glfwGetJoystickButtons(arg0, arg1)
}

fn C.glfwGetJoystickHats(i32, &i32) &u8
pub fn get_joystick_hats(arg0 i32, arg1 &i32) &u8 {
	return C.glfwGetJoystickHats(arg0, arg1)
}

fn C.glfwGetJoystickName(i32) &char
pub fn get_joystick_name(arg0 i32) &char {
	return C.glfwGetJoystickName(arg0)
}

fn C.glfwGetJoystickGUID(i32) &char
pub fn get_joystick_g_u_i_d(arg0 i32) &char {
	return C.glfwGetJoystickGUID(arg0)
}

fn C.glfwSetJoystickUserPointer(i32, voidptr)
pub fn set_joystick_user_pointer(arg0 i32, arg1 voidptr) {
	C.glfwSetJoystickUserPointer(arg0, arg1)
}

fn C.glfwGetJoystickUserPointer(i32) voidptr
pub fn get_joystick_user_pointer(arg0 i32) voidptr {
	return C.glfwGetJoystickUserPointer(arg0)
}

fn C.glfwJoystickIsGamepad(i32) i32
pub fn joystick_is_gamepad(arg0 i32) i32 {
	return C.glfwJoystickIsGamepad(arg0)
}

fn C.glfwSetJoystickCallback(GLFWjoystickfun) GLFWjoystickfun
pub fn set_joystick_callback(arg0 GLFWjoystickfun) GLFWjoystickfun {
	return C.glfwSetJoystickCallback(arg0)
}

fn C.glfwUpdateGamepadMappings(&char) i32
pub fn update_gamepad_mappings(arg0 &char) i32 {
	return C.glfwUpdateGamepadMappings(arg0)
}

fn C.glfwGetGamepadName(i32) &char
pub fn get_gamepad_name(arg0 i32) &char {
	return C.glfwGetGamepadName(arg0)
}

fn C.glfwGetGamepadState(i32, &GamepadState) i32
pub fn get_gamepad_state(arg0 i32, arg1 &GamepadState) i32 {
	return C.glfwGetGamepadState(arg0, arg1)
}

fn C.glfwSetClipboardString(&Window, &char)
pub fn set_clipboard_string(arg0 &Window, arg1 &char) {
	C.glfwSetClipboardString(arg0, arg1)
}

fn C.glfwGetClipboardString(&Window) &char
pub fn get_clipboard_string(arg0 &Window) &char {
	return C.glfwGetClipboardString(arg0)
}

fn C.glfwGetTime() f64
pub fn get_time() f64 {
	return C.glfwGetTime()
}

fn C.glfwSetTime(f64)
pub fn set_time(arg0 f64) {
	C.glfwSetTime(arg0)
}

fn C.glfwGetTimerValue() u64
pub fn get_timer_value() u64 {
	return C.glfwGetTimerValue()
}

fn C.glfwGetTimerFrequency() u64
pub fn get_timer_frequency() u64 {
	return C.glfwGetTimerFrequency()
}

fn C.glfwGetCurrentContext() &Window
pub fn get_current_context() &Window {
	return C.glfwGetCurrentContext()
}

fn C.glfwSwapBuffers(&Window)
pub fn swap_buffers(arg0 &Window) {
	C.glfwSwapBuffers(arg0)
}

fn C.glfwSwapInterval(i32)
pub fn swap_interval(arg0 i32) {
	C.glfwSwapInterval(arg0)
}

fn C.glfwExtensionSupported(&char) i32
pub fn extension_supported(arg0 &char) i32 {
	return C.glfwExtensionSupported(arg0)
}

fn C.glfwGetProcAddress(&char) voidptr
pub fn get_proc_address(arg0 &char) voidptr {
	return C.glfwGetProcAddress(arg0)
}

fn C.glfwGetInstanceProcAddress(vk.Instance, &char) voidptr
pub fn get_instance_proc_address(arg0 vk.Instance, arg1 &char) voidptr {
	return C.glfwGetInstanceProcAddress(arg0, arg1)
}
